# application.properties == application.yml
# ??? ????? ? ? ?? ???? ??? ??? ??.
# ?? ???? ?? ? ? ??.
# yml ? json ??? ??? ???? ???? ?? ???? superset ??.
# ?? ? ??
# ? ???? ??? ???? ?? spring? ?? ?? ????
# ???? ?? ? ? ??. -> ???? JSON ? ??? ?? ? ? ??

spring:
  #
  application:
    name: thyme
  #
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
# live reloading ? ? ? ??. -> cache: false
  #
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 1234

# spring.application.name=thyme
# spring.thymeleaf.cache=false